### ISSUE TITLE
Not able to parse float32[]

### ISSUE THREAD

**Issue by kshitijgoel007** [michaeljenkin/unityros#1]
I am trying to subscribe to a rosmsg that looks like this : 

std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
uint8 order
float32[] knot_times
float32[] coefficients
float32 sample_dt

I debugged a little bit and found out that my message file is not able to parse a float32 array. If I just take a byte, it works fine.

**Comment by michaeljenkin** [comment]
Hi - travelling by bus in Italy at present. I’ll have a look next week when I am back. Michael

**Comment by rcodddow** [comment]
Can you post your code for the RosbridgeMsg subclass you wrote.

**Comment by kshitijgoel007** [comment]
Hey, Last night I debugged a lot and found out the mistake. SimpleJSON is producing some error while reading float32[] arrays. Because of that reason my code was not progressing further and client was getting disconnected.

Here is the rosmsg : 
`std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
uint8 order
float32[] knot_times
float32[] coefficients
float32 sample_dt
`
Here is the data I receive as a string : 
`{"header":{"stamp":{"secs":"1556", "nsecs":"843999970"}, "seq":"205"}, "knot_times":[ "0.0", "0.013995146378874779" ], "sample_dt":"0.10000000149011612", "order":"13", "coefficients":[ "-37.4166145324707", "-0.9950066804885864", "0.0", "-1.1314932416581561e-13", "4.042448667473941e-12", "1.1509042789372165e-24", "-9.137328533520666e-23", "1.865407593838759e-21", "-1.1689548742845434e-35", "4.949672889284118e-34", "-7.073413829166279e-33", "0.0", "0.0", "0.0", "-10.341546058654785", "-0.09980829060077667", "0.0", "1.128005783397612e-12", "-4.0299895365247806e-11", "1.1544624360502158e-25", "-9.165578431397536e-24", "1.8711749117406191e-22", "1.1653519238322288e-34", "-4.9344174521688414e-33", "7.051612523188753e-32", "0.0", "0.0", "0.0", "2.1094725131988525", "1.1102230246251565e-16", "0.0", "0.0", "0.0", "-1.2841779386765489e-40", "1.0195380994038749e-38", "-2.081411611440607e-37", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0", "-3.0416178703308105", "0.0", "-3.400999750921563e-12", "1.6200853159009654e-10", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0", "0.0" ]}`

Here is the file _SplineMsg.cs_ in the newly created namespace _teleoperationsandbox_ :

`using ROSBridgeLib.std_msgs;
 using SimpleJSON;
 using UnityEngine;

 namespace ROSBridgeLib
 {
    namespace teleoperationsandbox
     {
         public class SplineMsg : ROSBridgeMsg
         {
             private byte _order;
             private float _sample_dt;
             private float[] _knot_times;
             private float[] _coefficients;
             int i;

```
        public SplineMsg(JSONNode msg)
        {
             _order = byte.Parse(msg["order"]);
             //Just testing for knot_times right now. Will integrate coefficients later.
             for(i=0; i<2; i++)
             {
                   _knot_times[i] = float.Parse(msg["knot_times"]);
              }
        }

        public static string getMessageType()
        {
            return "quadrotor_msgs/Spline";
        }

        public float GetOrder()
        {
            return _order;
        }

        public string GetCoefficients()
        {
            return _coefficients;
        }

        public float[] GetKnotTimes()
        {
            return _knot_times;
        }    

        public override string ToString()
        {
            return "quarotor_msgs/Spline [seq=" + ",  secs=" + ", nsecs=" +
                ", order=" + _order + ", knot_times=" + _knot_times + ", coefficients=" + _coefficients + "]";
        }

        public override string ToYAMLString()
        {
            return "{\"seq\": " + ", \"secs\": " + ", \"nsecs\": "+", \"order\": " + _order + ", \"knot_times\": " + _knot_times + ", \"coefficients\": " + _coefficients + "}";
        }
    }
}
```

}
`

**Comment by kshitijgoel007** [comment]
Thank you. I was able to resolve this issue by : 

`
                var N = JSON.Parse(msg.ToString());

```
            _order = byte.Parse(msg["order"]);
            double[] temp1 = new double[2] { Convert.ToDouble(N["knot_times"][0]), Convert.ToDouble(N["knot_times"][1]) };
            _knot_times = temp1;
            Matrix temp2 = new Matrix(4, (_order + 1));

            for (int j = 0; j < 4; j++)
            { 
                int i = (j)*(_order + 1);
                while (i < ((_order + 1) * (j + 1)))
                {

                    temp2[j, i - (_order + 1)*j] = Convert.ToDouble(N["coefficients"][i]);
                    i++;
                }
            }

            _coefficients = temp2;`
```
