### ISSUE TITLE
Failed to send StringMsg

### ISSUE THREAD

**Issue by arunavanag591** [michaeljenkin/unityros#11]
Hello,

I am trying to follow example from the submodule developed [here](https://github.com/MathiasCiarlo/ROSBridgeLib)

I am trying to check my connection by sending string message, however, my final intention is to send an array of integer values coming from slider position I have.

Presently I am trying this:

```
#if UNITY_EDITOR
    void Start(){

        ros = new ROSBridgeLib.ROSBridgeWebSocketConnection("ws://192.168.142.67", 9090);
        ros.AddPublisher(typeof(ROSCommsSlider));

        
       
    }
#endif
#if UNITY_EDITOR
    private void OnApplicationQuit(){
        if (ros != null) {
            ros.Disconnect();
        }
    }
#endif

#if UNITY_EDITOR
    public void my_func() {
       
    }
#endif

    // Update is called once per frame
    void Update() {
#if UNITY_EDITOR
        if (Input.GetKeyDown(KeyCode.C))
        {
            ros.Connect();
        }
        
        //ros.Render();
        ROSBridgeLib.std_msgs.StringMsg ms = new ROSBridgeLib.std_msgs.StringMsg("checking_connection");
        ros.Publish(ROSCommsSlider.GetMessageTopic(), ms);
#endif
}

```
my ROSCommsSlider looks like this:

```
public class ROSCommsSlider : ROSBridgeLib.ROSBridgePublisher {
    // my class for sending message to ROSbridge
    public static string GetMessageTopic()
    {
        return "/joint_values";
    }
        public static string GetMessageType()
    {
        return "std_msgs/String";
    }

    public static string ToYAMLString(ROSBridgeLib.std_msgs.StringMsg msg)
    {
        return msg.ToYAMLString();
    }

    public new static ROSBridgeMsg ParseMessage(JSONNode msg)
    {
        return new ROSBridgeLib.std_msgs.StringMsg(msg);
    }

}
```
When I run the ros bridge, for some reason it is creating 3 client connection instance, but however, it doesn't send in the string to my topic when I do: 
`rostopic echo /joint_values`

I do get this in my unity console:

```
Sending {"op": "advertise", "topic": "/joint_values", "type": "std_msgs/String"}
UnityEngine.Debug:Log(Object)
ROSBridgeLib.ROSBridgeWebSocketConnection:Run() (at Assets/ROSBridgeLib/ROSBridgeWebSocketConnection.cs:195)
```
and an error:

```
InvalidOperationException: The current state of the connection is not Open.
WebSocketSharp.WebSocket.Send (System.String data)
ROSBridgeLib.ROSBridgeWebSocketConnection.Publish (System.String topic, .ROSBridgeMsg msg) (at Assets/ROSBridgeLib/ROSBridgeWebSocketConnection.cs:264)
ROSCommsMain.Update () (at Assets/Scripts/ROSCommsMain.cs:73)
```

which i dont understand why as under my rosbridge shows: `Clients Connected.`

Additionally, I receive this Null Reference Issue when close the unity editor play.

```
NullReferenceException: Object reference not set to an instance of an object

ROSBridgeLib.ROSBridgeWebSocketConnection.Disconnect () (at Assets/ROSBridgeLib/ROSBridgeWebSocketConnection.cs:170)
ROSCommsMain.OnApplicationQuit () (at Assets/Scripts/ROSCommsMain.cs:27)
```

**Comment by arunavanag591** [comment]
Hello @michaeljenkin  kindly review and please reply.

**Comment by arunavanag591** [comment]
Hello is there any update on this

**Comment by michaeljenkin** [comment]
To publish you need to extend a ROSBridgePublisher

public class Turtle1Teleop: ROSBridgePublisher {
    
    public static string GetMessageTopic() {
        return "/turtle1/cmd_vel";
    }  
    
    public static string GetMessageType() {
        return "geometry_msgs/Twist";
    }

    public static string ToYAMLString(VelocityMsg msg) {
        return msg.ToYAMLString ();
    }
}

(See the example code).  So to publish a string as AliveMessage in /robot1 of type string

public class ImAliveString: ROSBridgePublisher {
    
    public static string GetMessageTopic() {
        return “/robot1/AliveMessage";
    }  
    
    public static string GetMessageType() {
        return “std_msgs/String";
    }

    public static string ToYAMLString(VelocityMsg msg) {
        return msg.ToYAMLString ();
    }
}


Then say so 

ros.AddPublisher(typeof(ImAliveString));

And then publish as

ROSBridgeLib.std_msgs.StringMsg msg = new ROSBridgeLib.std_msgs.StringMsg(“heartbeat”);
ros.Publish (ImAliveString.GetMessageTopic (), msg);  

Hope this helps

Michael

**Comment by arunavanag591** [comment]
I @michaeljenkin I have now been able to do this. I actually could send string from ROS to Unity. However strangely, from unity to ROS, it does not show up in my terminal nodes. 

However, I have checked, I am sending the right strings. My rosbridge shows one client is connected. But the message does not reflect under my topic. Just to make sure, I even used wireshark to sniff my wlan, and found the whole rosbridge message is going as per the semantics. So I narrowed down the issue, it has to be my ros node. Do i need have to build my string data model. 

I advertise first:

`{"op": "advertise", "topic": "/talker", "type": "std_msgs/String"}`
which reflects over ros bridge as 1 client is connected.

Then I publish my message:

`{"op": "publish", "topic": "/talker", "msg": {"data" : _my_message }}`
I even wrote a ros publisher node looks like this; though I could just do `rostopic echo /talker` ; as the talker appears, and when i do: `rostopic info /talker`, it shows publisher as `rosbridge_websocket` . But just cant understand where is the message lost.
```

#include "ros/ros.h"
#include "std_msgs/String.h"

int main(int argc, char **argv)
{
  ros::init(argc, argv, "pub_node");
  ros::NodeHandle n; 
  ros::Publisher chatter_pub = n.advertise<std_msgs::String>("talker", 0);
  std_msgs::String msg;
  ROS_INFO("%s", msg.data.c_str());
  chatter_pub.publish(msg);
  ros::spin();
  return 0;
}
```
and my subscriber node: (just using straight away from the tutorial)

```
#include "ros/ros.h"
#include "std_msgs/String.h"

void chatterCallback(const std_msgs::String::ConstPtr& msg)
{
  ROS_INFO("I heard: [%s]", msg->data.c_str());
}

int main(int argc, char **argv)
{

  ros::init(argc, argv, "sub_node");
  ros::NodeHandle n;
  ros::Subscriber sub = n.subscribe("talker", 0, chatterCallback);
  ros::spin();
  return 0;
}
```
But I never receive any message. I have converted my message into JSON as per rosbridge protocol: `{ "op": "publish",(optional) "id": <string>,"topic": <string>, "msg": <json>}
`



My unity side seems like the same u have advised:
```
public class ROSBridgeComm : MonoBehaviour {

    private ROSBridgeLib.ROSBridgeWebSocketConnection ros = null;
   
  
    void Start(){
        ros = new ROSBridgeLib.ROSBridgeWebSocketConnection("ws://192.168.137.175", 9090);
        ros.AddPublisher(typeof(PubSliderValue));
        ros.AddSubscriber(typeof(Sub));
        ros.Connect();


    }
    void OnApplicationQuit()
    {
        if (ros != null)
        {
            ros.Disconnect();
        }
    }

    // Update is called once per frame
    void Update(){

        if (Input.GetKey(KeyCode.C))
        {
            ROSBridgeLib.std_msgs.StringMsg msg = new ROSBridgeLib.std_msgs.StringMsg("_my_message ");
            ros.Publish(PubSliderValue.GetMessageTopic(), msg);
            Debug.Log(msg);
        }
        ros.Render();
    }

}
```
This is my publishvalue script:
```

public class PubSliderValue : ROSBridgeLib.ROSBridgePublisher {

    public new static string GetMessageTopic() {

        return "/talker";
    }

    public new static string GetMessageType()
    {
        return "std_msgs/String";
    }

    public static string ToYAMLString(ROSBridgeLib.std_msgs.StringMsg msg)
    {
        return msg.ToYAMLString();
    }
   /* public static ROSBridgeMsg ParseMessage(SimpleJSON.JSONNode msg)
    {
        return new ROSBridgeLib.std_msgs.StringMsg(msg);
    }*/

   
}
```

and my rosbridgepublisher:

```
namespace ROSBridgeLib {
	public class ROSBridgePublisher {
		
		public static string GetMessageTopic() {
			return null;
		}  
		
		public static string GetMessageType() {
			return null;
		}

		public static string ToYAMLString() {
			return null;
		}
	}
}
```
Any pointers on this?

**Comment by arunavanag591** [comment]
Ok, I resolved it.
I had to change StringMsg.cs.
FYI: i am using Ros Kinetic
```
public override string ToYAMLString() {
	return "{\"data\" : " + "\" " +  _data + "\" " + "}";
}
```

**Comment by Shreepati** [comment]
Hey I had the same problem, i was not able to publish into ROS from unity. My fix was ,
1. Run ROS core
2. Run Rosbridge (cmd : roslaunch rosbridge_server rosbridge_websocket.launch)
3. Run the unity scripts.
And volia, you should be publishing into ROS,
You should be seeing the topic published under rostopic list.
