### ISSUE TITLE
Can't read sensor_msgs/PointCloud

### ISSUE THREAD

**Issue by kshitijgoel007** [michaeljenkin/unityros#2]
Is there an upper bound to the data that can be transmitted through rosbridge? I am not able to transfer my point cloud message in time and there's too much lag in transferring.

I saw this [paper](http://vgrserver.cs.yorku.ca/~jenkin/papers/2014/ros2unity.pdf) and I'm curious as to how it is achieved in real-time using this repository.

**Comment by michaeljenkin** [comment]
ROSBridge passes the data as 7 bit clean data (aka ascii) by default. So if you large amounts of sensor data through a small pipe its going to be unpleasant.

We normally throttle high bandwidth messages prior to pumping them out through ROSBridge. 

For static maps (like the one in the paper), you can pre-position the full map and only the robot pose and the laser scans need to be updated live.

Michael
